zuul.ignored-services: "*"
zuul.prefix: /api
zuul.routes.organizationservice: /organization/**
zuul.routes.licensingservice: /licensing/**
zuul.routes.authenticationservice: /auth/**
zuul.sensitiveHeaders: Cookie,Set-Cookie
zuul.debug.request: true